name: Deploy
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Yarn
        run: npm install -g yarn@1.22.10
      - run: yarn install --frozen-lockfile
 
      - name: Build
        run: yarn docs:build
 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
